[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  
[build]
  command = "echo 'No build needed'"
  
[build.environment]
  NODE_VERSION = "22"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/app/:splat"